// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { resolve } from "path";
import { fileURLToPath } from "url";
import { dirname } from "path";
import { defineConfig } from "prisma/config";

// Explicitly load root .env to ensure consistent behavior regardless of CWD
const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

config({ path: resolve(__dirname, "../../.env") });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Should be ablet to use env() later on https://github.com/prisma/prisma/issues/12535
    url: process.env.DATABASE_URL!,
  },
});
